---
name: POE-Component-IRC-Plugin-HTML-ElementInfo
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: lookup HTML element information from IRC
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE::Component::IRC::Plugin::BaseWrap: 0.001
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::HTML::ElementInfo:
    file: lib/POE/Component/IRC/Plugin/HTML/ElementInfo.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
